#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $VORTEX_REPO == "vortexub" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thbmVraWtlbjQ0L1ZvcnRleFVCL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $VORTEX_REPO == "VORTEXUB" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thbmVraWtlbjQ0L1ZvcnRleFVCL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $VORTEX_REPO =~ $regex ]]
    then
        if [[ $VORTEX_REPO_BRANCH ]]
        then
            echo "${VORTEX_REPO}/archive/${VORTEX_REPO_BRANCH}.zip"
        else
            echo "${VORTEX_REPO}/archive/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thbmVraWtlbjQ0L1ZvcnRleFVCL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    fi
}


_starter () {
    local zippath
    zippath="vortexub.zip"
    echo "••• DOWNLOADING VORTEXUB •••"
    wget -q $(_get_repolink) -O "$zippath"
    VORTEX_PATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    rm -rf "$zippath"
    sleep 5
    cd $VORTEX_PATH
    echo "•• Starting Vortex Userbot ••"

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Vortex
}

_starter
