#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $VORTEX_REPO == "vortexub" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $VORTEX_REPO == "VORTEXUB" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $VORTEX_REPO =~ $regex ]]
    then
        if [[ $VORTEX_REPO_BRANCH ]]
        then
            echo "${VORTEX_REPO}/archive/${HELL_REPO_BRANCH}.zip"
        else
            echo "${VORTEX_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_starter () {
    local zippath
    zippath="vortexub.zip"
    echo "••• DOWNLOADING VORTEXUB •••"
    wget -q $(_get_repolink) -O "$zippath"
    VORTEX_PATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    rm -rf "$zippath"
    sleep 5
    cd $VORTEX_PATH
    echo "••• STARTING VORTEX USERBOT •••"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m vortex
}

_starter
